/** @typedef {import('./destination-details-view').DestinationPictureState} DestinationPictureState */
/** @typedef {import('./destination-select-view').DestinationOptionState} DestinationOptionState */
/** @typedef {import('./offer-select-view').OfferSelectState} OfferSelectState */
/** @typedef {import('./offer-view').OfferState} OfferState  */
/** @typedef {import('./offer-toggle-view').OfferToggleState} OfferToggleState  */
/** @typedef {import('./sort-options-view').SortOptionState} SortOptionState */
/** @typedef {import('./type-option-view').TypeOptionState} TypeOptionState */
/** @typedef {import('./point-view').PointState} PointState */
/** @typedef {import('./point-list-view').default} PointListView */
/** @typedef {import('./editor-view').default} EditorView */
